server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/api/v1/loans/**
        - id: loan-group-service
          uri: lb://LOAN-GROUP-SERVICE
          predicates:
            - Path=/api/v1/loan_group/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user_service/**
        - id: investment-service
          uri: lb://INVESTMENT-SERVICE
          predicates:
            - Path=/api/v1/invest-service/**
        - id: repayment-service
          uri: lb://REPAYMENT-SERVICE
          predicates:
            - Path=/api/v1/repayment-service/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true